List<String> data_Metieye_title = [
  "점검대상",
  "전수검사",
  "완료 서버수",
  "점검율",
  "알림기능 설정",
  "완료 서버수",
  "설정율",
  "탐지디렉토리 설정",
  "완료 서버수",
  "설정율",
  "실시간탐지 설정",
  "완료 서버수",
  "설정율",
  "진행율"
];

List<Map<String, dynamic>> data_metieye_data = [
  {
    "target": 9,
    "done_check": 1,
    "rate_check": "11%",
    "done_alarm": 1,
    "rate_alarm": "11%",
    "done_direc": 1,
    "rate_direc": "11%",
    "done_live": 1,
    "rate_live": "11%",
    "rate": "11%"
  },
  {
    "target": 62,
    "done_check": 2,
    "rate_check": "3%",
    "done_alarm": 2,
    "rate_alarm": "3%",
    "done_direc": 2,
    "rate_direc": "3%",
    "done_live": 2,
    "rate_live": "3%",
    "rate": "3%"
  },
  {
    "target": 76,
    "done_check": 3,
    "rate_check": "3%",
    "done_alarm": 3,
    "rate_alarm": "3%",
    "done_direc": 3,
    "rate_direc": "3%",
    "done_live": 3,
    "rate_live": "3%",
    "rate": "3%"
  },
  {
    "target": 57,
    "done_check": 4,
    "rate_check": "7%",
    "done_alarm": 4,
    "rate_alarm": "7%",
    "done_direc": 4,
    "rate_direc": "7%",
    "done_live": 4,
    "rate_live": "7%",
    "rate": "7%"
  },
  {
    "target": 80,
    "done_check": 5,
    "rate_check": "6%",
    "done_alarm": 5,
    "rate_alarm": "6%",
    "done_direc": 5,
    "rate_direc": "6%",
    "done_live": 5,
    "rate_live": "6%",
    "rate": "6%"
  },
  {
    "target": 12,
    "done_check": 6,
    "rate_check": "50%",
    "done_alarm": 6,
    "rate_alarm": "50%",
    "done_direc": 6,
    "rate_direc": "50%",
    "done_live": 6,
    "rate_live": "50%",
    "rate": "50%"
  },
  {
    "target": 54,
    "done_check": 7,
    "rate_check": "12%",
    "done_alarm": 7,
    "rate_alarm": "12%",
    "done_direc": 7,
    "rate_direc": "12%",
    "done_live": 7,
    "rate_live": "12%",
    "rate": "12%"
  },
  {
    "target": 86,
    "done_check": 8,
    "rate_check": "9%",
    "done_alarm": 8,
    "rate_alarm": "9%",
    "done_direc": 8,
    "rate_direc": "9%",
    "done_live": 8,
    "rate_live": "9%",
    "rate": "9%"
  },
  {
    "target": 24,
    "done_check": 9,
    "rate_check": "37%",
    "done_alarm": 9,
    "rate_alarm": "37%",
    "done_direc": 9,
    "rate_direc": "37%",
    "done_live": 9,
    "rate_live": "37%",
    "rate": "37%"
  },
  {
    "target": 93,
    "done_check": 10,
    "rate_check": "10%",
    "done_alarm": 10,
    "rate_alarm": "10%",
    "done_direc": 10,
    "rate_direc": "10%",
    "done_live": 10,
    "rate_live": "10%",
    "rate": "10%"
  },
  {
    "target": 36,
    "done_check": 11,
    "rate_check": "30%",
    "done_alarm": 11,
    "rate_alarm": "30%",
    "done_direc": 11,
    "rate_direc": "30%",
    "done_live": 11,
    "rate_live": "30%",
    "rate": "30%"
  },
  {
    "target": 7,
    "done_check": 2,
    "rate_check": "28%",
    "done_alarm": 2,
    "rate_alarm": "28%",
    "done_direc": 2,
    "rate_direc": "28%",
    "done_live": 2,
    "rate_live": "28%",
    "rate": "28%"
  },
  {
    "target": 11,
    "done_check": 1,
    "rate_check": "9%",
    "done_alarm": 1,
    "rate_alarm": "9%",
    "done_direc": 1,
    "rate_direc": "9%",
    "done_live": 1,
    "rate_live": "9%",
    "rate": "9%"
  },
  {
    "target": 457,
    "done_check": 14,
    "rate_check": "3%",
    "done_alarm": 14,
    "rate_alarm": "3%",
    "done_direc": 14,
    "rate_direc": "3%",
    "done_live": 14,
    "rate_live": "3%",
    "rate": "3%"
  },
  {
    "target": 78,
    "done_check": 15,
    "rate_check": "19%",
    "done_alarm": 15,
    "rate_alarm": "19%",
    "done_direc": 15,
    "rate_direc": "19%",
    "done_live": 15,
    "rate_live": "19%",
    "rate": "19%"
  },
  {
    "target": 2,
    "done_check": 2,
    "rate_check": "100%",
    "done_alarm": 2,
    "rate_alarm": "100%",
    "done_direc": 2,
    "rate_direc": "100%",
    "done_live": 2,
    "rate_live": "100%",
    "rate": "100%"
  },
  {
    "target": 2,
    "done_check": 1,
    "rate_check": "50%",
    "done_alarm": 1,
    "rate_alarm": "50%",
    "done_direc": 1,
    "rate_direc": "50%",
    "done_live": 1,
    "rate_live": "50%",
    "rate": "50%"
  },
  {
    "target": 1146,
    "done_check": 101,
    "rate_check": "22%",
    "done_alarm": 101,
    "rate_alarm": "22%",
    "done_direc": 101,
    "rate_direc": "22%",
    "done_live": 101,
    "rate_live": "22%",
    "rate": "22%"
  }
];
