List<String> data_Metieye_title = [
  "점검대상",
  "Agent 설치",
  "미설치 서버수",
  "설치율",
  "탐지디렉토리 설정",
  "미완료 서버수",
  "설정율",
  "실시간탐지 설정",
  "미완료 서버수",
  "설정율",
  "알림기능 설정",
  "미완료 서버수",
  "설정율",
  "전수검사",
  "미완료 서버수",
  "점검율",
  "진행율"
];

List<Map<String, dynamic>> data_metieye_data = [
  {
    "target": 7,
    "done_agent": 0,
    "rate_agent": "100%",
    "done_direc": 0,
    "rate_direc": "100%",
    "done_live": 0,
    "rate_live": "100%",
    "done_alarm": 0,
    "rate_alarm": "100%",
    "done_check": 0,
    "rate_check": "100%",
    "rate": "100%"
  },
  {
    "target": 63,
    "done_agent": 23,
    "rate_agent": "63%",
    "done_direc": 23,
    "rate_direc": "63%",
    "done_live": 23,
    "rate_live": "63%",
    "done_alarm": 23,
    "rate_alarm": "63%",
    "done_check": 23,
    "rate_check": "63%",
    "rate": "63%"
  },
  {
    "target": 52,
    "done_agent": 0,
    "rate_agent": "100%",
    "done_direc": 0,
    "rate_direc": "100%",
    "done_live": 6,
    "rate_live": "88%",
    "done_alarm": 16,
    "rate_alarm": "69%",
    "done_check": 1,
    "rate_check": "98%",
    "rate": "91%"
  },
  {
    "target": 24,
    "done_agent": 24,
    "rate_agent": "0%",
    "done_direc": 24,
    "rate_direc": "0%",
    "done_live": 24,
    "rate_live": "0%",
    "done_alarm": 24,
    "rate_alarm": "0%",
    "done_check": 24,
    "rate_check": "0%",
    "rate": "0%"
  },
  {
    "target": 79,
    "done_agent": 0,
    "rate_agent": "100%",
    "done_direc": 0,
    "rate_direc": "100%",
    "done_live": 15,
    "rate_live": "81%",
    "done_alarm": 4,
    "rate_alarm": "94%",
    "done_check": 7,
    "rate_check": "91%",
    "rate": "93%"
  },
  {
    "target": 10,
    "done_agent": 3,
    "rate_agent": "70%",
    "done_direc": 3,
    "rate_direc": "70%",
    "done_live": 3,
    "rate_live": "70%",
    "done_alarm": 3,
    "rate_alarm": "70%",
    "done_check": 3,
    "rate_check": "70%",
    "rate": "70%"
  },
  {
    "target": 52,
    "done_agent": 31,
    "rate_agent": "40%",
    "done_direc": 31,
    "rate_direc": "40%",
    "done_live": 31,
    "rate_live": "40%",
    "done_alarm": 33,
    "rate_alarm": "36%",
    "done_check": 31,
    "rate_check": "40%",
    "rate": "39%"
  },
  {
    "target": 44,
    "done_agent": 0,
    "rate_agent": "100%",
    "done_direc": 0,
    "rate_direc": "100%",
    "done_live": 1,
    "rate_live": "97%",
    "done_alarm": 0,
    "rate_alarm": "100%",
    "done_check": 0,
    "rate_check": "100%",
    "rate": "99%"
  },
  {
    "target": 8,
    "done_agent": 0,
    "rate_agent": "100%",
    "done_direc": 0,
    "rate_direc": "100%",
    "done_live": 0,
    "rate_live": "100%",
    "done_alarm": 0,
    "rate_alarm": "100%",
    "done_check": 0,
    "rate_check": "100%",
    "rate": "100%"
  },
  {
    "target": 89,
    "done_agent": 30,
    "rate_agent": "66%",
    "done_direc": 30,
    "rate_direc": "66%",
    "done_live": 48,
    "rate_live": "46%",
    "done_alarm": 45,
    "rate_alarm": "49%",
    "done_check": 31,
    "rate_check": "65%",
    "rate": "58%"
  },
  {
    "target": 32,
    "done_agent": 1,
    "rate_agent": "96%",
    "done_direc": 2,
    "rate_direc": "93%",
    "done_live": 31,
    "rate_live": "3%",
    "done_alarm": 1,
    "rate_alarm": "96%",
    "done_check": 1,
    "rate_check": "96%",
    "rate": "76%"
  },
  {
    "target": 6,
    "done_agent": 1,
    "rate_agent": "83%",
    "done_direc": 1,
    "rate_direc": "83%",
    "done_live": 1,
    "rate_live": "83%",
    "done_alarm": 1,
    "rate_alarm": "83%",
    "done_check": 1,
    "rate_check": "83%",
    "rate": "83%"
  },
  {
    "target": 11,
    "done_agent": 11,
    "rate_agent": "0%",
    "done_direc": 11,
    "rate_direc": "0%",
    "done_live": 11,
    "rate_live": "0%",
    "done_alarm": 11,
    "rate_alarm": "0%",
    "done_check": 11,
    "rate_check": "0%",
    "rate": "0%"
  },
  {
    "target": 372,
    "done_agent": 137,
    "rate_agent": "63%",
    "done_direc": 137,
    "rate_direc": "63%",
    "done_live": 151,
    "rate_live": "59%",
    "done_alarm": 140,
    "rate_alarm": "62%",
    "done_check": 137,
    "rate_check": "63%",
    "rate": "62%"
  },
  {
    "target": 42,
    "done_agent": 2,
    "rate_agent": "95%",
    "done_direc": 23,
    "rate_direc": "45%",
    "done_live": 41,
    "rate_live": "2%",
    "done_alarm": 2,
    "rate_alarm": "95%",
    "done_check": 2,
    "rate_check": "95%",
    "rate": "66%"
  },
  {
    "target": 2,
    "done_agent": 0,
    "rate_agent": "100%",
    "done_direc": 0,
    "rate_direc": "100%",
    "done_live": 0,
    "rate_live": "100%",
    "done_alarm": 0,
    "rate_alarm": "100%",
    "done_check": 0,
    "rate_check": "100%",
    "rate": "100%"
  },
  {
    "target": 2,
    "done_agent": 2,
    "rate_agent": "0%",
    "done_direc": 2,
    "rate_direc": "0%",
    "done_live": 2,
    "rate_live": "0%",
    "done_alarm": 2,
    "rate_alarm": "0%",
    "done_check": 2,
    "rate_check": "0%",
    "rate": "0%"
  },
  {
    "target": 895,
    "done_agent": 265,
    "rate_agent": "69%",
    "done_direc": 287,
    "rate_direc": "66%",
    "done_live": 388,
    "rate_live": "54%",
    "done_alarm": 305,
    "rate_alarm": "65%",
    "done_check": 274,
    "rate_check": "68%",
    "rate": "64%"
  }
];
