List<String> data_Metieye_title = [
  "점검대상",
  "Agent 설치",
  "미설치 서버수",
  "설치율",
  "탐지디렉토리 설정",
  "미완료 서버수",
  "설정율",
  "실시간탐지 설정",
  "미완료 서버수",
  "설정율",
  "알림기능 설정",
  "미완료 서버수",
  "설정율",
  "전수검사",
  "미완료 서버수",
  "점검율",
  "진행율"
];

List<Map<String, dynamic>> data_metieye_data = [
  {
    "target": 7,
    "done_agent": 0,
    "rate_agent": "100%",
    "done_direc": 0,
    "rate_direc": "100%",
    "done_live": 0,
    "rate_live": "100%",
    "done_alarm": 0,
    "rate_alarm": "100%",
    "done_check": 0,
    "rate_check": "100%",
    "rate": "100%"
  },
  {
    "target": 41,
    "done_agent": 0,
    "rate_agent": "100%",
    "done_direc": 0,
    "rate_direc": "100%",
    "done_live": 0,
    "rate_live": "100%",
    "done_alarm": 0,
    "rate_alarm": "100%",
    "done_check": 0,
    "rate_check": "100%",
    "rate": "100%"
  },
  {
    "target": 52,
    "done_agent": 0,
    "rate_agent": "100%",
    "done_direc": 0,
    "rate_direc": "100%",
    "done_live": 0,
    "rate_live": "100%",
    "done_alarm": 0,
    "rate_alarm": "100%",
    "done_check": 0,
    "rate_check": "100%",
    "rate": "100%"
  },
  {
    "target": 13,
    "done_agent": 0,
    "rate_agent": "100%",
    "done_direc": 1,
    "rate_direc": "92%",
    "done_live": 1,
    "rate_live": "92%",
    "done_alarm": 1,
    "rate_alarm": "92%",
    "done_check": 0,
    "rate_check": "100%",
    "rate": "95%"
  },
  {
    "target": 64,
    "done_agent": 0,
    "rate_agent": "100%",
    "done_direc": 0,
    "rate_direc": "100%",
    "done_live": 0,
    "rate_live": "100%",
    "done_alarm": 0,
    "rate_alarm": "100%",
    "done_check": 0,
    "rate_check": "100%",
    "rate": "100%"
  },
  {
    "target": 7,
    "done_agent": 0,
    "rate_agent": "100%",
    "done_direc": 0,
    "rate_direc": "100%",
    "done_live": 0,
    "rate_live": "100%",
    "done_alarm": 0,
    "rate_alarm": "100%",
    "done_check": 0,
    "rate_check": "100%",
    "rate": "100%"
  },
  {
    "target": 31,
    "done_agent": 5,
    "rate_agent": "83%",
    "done_direc": 5,
    "rate_direc": "83%",
    "done_live": 5,
    "rate_live": "83%",
    "done_alarm": 5,
    "rate_alarm": "83%",
    "done_check": 5,
    "rate_check": "83%",
    "rate": "83%"
  },
  {
    "target": 45,
    "done_agent": 0,
    "rate_agent": "100%",
    "done_direc": 1,
    "rate_direc": "97%",
    "done_live": 1,
    "rate_live": "97%",
    "done_alarm": 0,
    "rate_alarm": "100%",
    "done_check": 1,
    "rate_check": "97%",
    "rate": "98%"
  },
  {
    "target": 8,
    "done_agent": 0,
    "rate_agent": "100%",
    "done_direc": 0,
    "rate_direc": "100%",
    "done_live": 0,
    "rate_live": "100%",
    "done_alarm": 0,
    "rate_alarm": "100%",
    "done_check": 0,
    "rate_check": "100%",
    "rate": "100%"
  },
  {
    "target": 72,
    "done_agent": 7,
    "rate_agent": "90%",
    "done_direc": 23,
    "rate_direc": "68%",
    "done_live": 23,
    "rate_live": "68%",
    "done_alarm": 25,
    "rate_alarm": "65%",
    "done_check": 9,
    "rate_check": "87%",
    "rate": "75%"
  },
  {
    "target": 11,
    "done_agent": 0,
    "rate_agent": "100%",
    "done_direc": 5,
    "rate_direc": "54%",
    "done_live": 5,
    "rate_live": "54%",
    "done_alarm": 0,
    "rate_alarm": "100%",
    "done_check": 0,
    "rate_check": "100%",
    "rate": "81%"
  },
  {
    "target": 6,
    "done_agent": 0,
    "rate_agent": "100%",
    "done_direc": 0,
    "rate_direc": "100%",
    "done_live": 0,
    "rate_live": "100%",
    "done_alarm": 0,
    "rate_alarm": "100%",
    "done_check": 0,
    "rate_check": "100%",
    "rate": "100%"
  },
  {
    "target": 9,
    "done_agent": 0,
    "rate_agent": "100%",
    "done_direc": 0,
    "rate_direc": "100%",
    "done_live": 0,
    "rate_live": "100%",
    "done_alarm": 0,
    "rate_alarm": "100%",
    "done_check": 0,
    "rate_check": "100%",
    "rate": "100%"
  },
  {
    "target": 337,
    "done_agent": 1,
    "rate_agent": "99%",
    "done_direc": 6,
    "rate_direc": "98%",
    "done_live": 6,
    "rate_live": "98%",
    "done_alarm": 1,
    "rate_alarm": "99%",
    "done_check": 1,
    "rate_check": "99%",
    "rate": "98%"
  },
  {
    "target": 40,
    "done_agent": 0,
    "rate_agent": "100%",
    "done_direc": 39,
    "rate_direc": "2%",
    "done_live": 39,
    "rate_live": "2%",
    "done_alarm": 0,
    "rate_alarm": "100%",
    "done_check": 0,
    "rate_check": "100%",
    "rate": "60%"
  },
  {
    "target": 2,
    "done_agent": 0,
    "rate_agent": "100%",
    "done_direc": 0,
    "rate_direc": "100%",
    "done_live": 0,
    "rate_live": "100%",
    "done_alarm": 0,
    "rate_alarm": "100%",
    "done_check": 0,
    "rate_check": "100%",
    "rate": "100%"
  },
  {
    "target": 2,
    "done_agent": 2,
    "rate_agent": "0%",
    "done_direc": 2,
    "rate_direc": "0%",
    "done_live": 2,
    "rate_live": "0%",
    "done_alarm": 2,
    "rate_alarm": "0%",
    "done_check": 2,
    "rate_check": "0%",
    "rate": "0%"
  },
  {
    "target": 747,
    "done_agent": 15,
    "rate_agent": "92%",
    "done_direc": 82,
    "rate_direc": "82%",
    "done_live": 82,
    "rate_live": "82%",
    "done_alarm": 34,
    "rate_alarm": "90%",
    "done_check": 18,
    "rate_check": "92%",
    "rate": "87%"
  }
];
