// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6n5Buox0ZiwFH29yEKFXn_2rzaOYivCM',
    appId: '1:595356602771:web:1c866950d80536bdb05866',
    messagingSenderId: '595356602771',
    projectId: 'picstorage-f5e87',
    authDomain: 'picstorage-f5e87.firebaseapp.com',
    storageBucket: 'picstorage-f5e87.appspot.com',
    measurementId: 'G-21BYQP9EWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5AYFbYNJEnWv3N2rbMr1MP3yZ1tNaZXg',
    appId: '1:595356602771:android:a208fe66820df662b05866',
    messagingSenderId: '595356602771',
    projectId: 'picstorage-f5e87',
    storageBucket: 'picstorage-f5e87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa8FmYe8ccNqysXWnKj2AZ_rBNyiuewUI',
    appId: '1:595356602771:ios:9633348977a1a61db05866',
    messagingSenderId: '595356602771',
    projectId: 'picstorage-f5e87',
    storageBucket: 'picstorage-f5e87.appspot.com',
    iosBundleId: 'com.example.a13CloudGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa8FmYe8ccNqysXWnKj2AZ_rBNyiuewUI',
    appId: '1:595356602771:ios:a02c1b0c16b6b5a4b05866',
    messagingSenderId: '595356602771',
    projectId: 'picstorage-f5e87',
    storageBucket: 'picstorage-f5e87.appspot.com',
    iosBundleId: 'com.example.a13CloudGallery.RunnerTests',
  );
}
